package cn.smbms.dao;

import cn.smbms.pojo.SmbmsRole;

public interface SmbmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int insert(SmbmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int insertSelective(SmbmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    SmbmsRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int updateByPrimaryKeySelective(SmbmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_role
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int updateByPrimaryKey(SmbmsRole record);
}