package cn.smbms.dao;

import cn.smbms.pojo.SmbmsAddress;

public interface SmbmsAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int insert(SmbmsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int insertSelective(SmbmsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    SmbmsAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int updateByPrimaryKeySelective(SmbmsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smbms_address
     *
     * @mbggenerated Wed Jun 19 17:39:54 CST 2019
     */
    int updateByPrimaryKey(SmbmsAddress record);
}